"use client";

import React from "react";
import Link from "next/link";
import { useState, useEffect } from "react";

import { Inter, Roboto_Mono } from "next/font/google";
import axios from "axios";

const inter = Inter({ subsets: ["greek-ext"], weight: "400" });

export const metadata = {
  title: "Users",
  description: "Generated by create next app",
};

export default function UsersProfile() {
  const [userData, setUserData] = useState([]);

  useEffect(() => {
    axios
      .get("http://localhost:3000/api/auth/users")
      .then((response) => setUserData(response.data.data));
  }, [userData]);

  return (
    <>
      {userData.length > 0 &&
        userData.map((users) => (
          <h2 key={users.Eposta}>{users.Isim} Profil Hesabı</h2>
        ))}
    </>
  );
}
