import React from "react";
import styles from "./styles.module.css";

export const metadata = {
  title: "AboutPage",
  description: "Generated by create next app",
};

export default function AboutLayout({ children }) {
  return (
    <>
      <nav>About Navbar</nav>
      <main className={styles.main}>{children}</main>
    </>
  );
}
